version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - apt update
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py --user
      - pip3 install awscli --upgrade --user
  build:
    commands:
      - export PATH=/root/.local/bin:$PATH
      - npm install
      - npx sls deploy